Functional V0.2
algosup/2023-2024-project-5-flutter-team-1 pull request #3
Opened 2024-05-17 13:11 UTC by PortetWilfried

2024-05-17 13:48 UTC, NanaChocolat approved these changes
Just the "adopte un candidat" should be in English ligne 55, you can continue.

2024-05-17 14:09 UTC, EnzoGuillouche requested changes
Reviewed for the functional specifications, they need changes to be merged.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +6. Specify the geographical area for job searching.
The geographical area should be asked before accessing to the home page.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +7. If a company expresses interest in the user’s profile, the connection process begins.
Before that, the job seeker must like the company first, to initiate the match.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +1. Download the application on a computer or mobile device.
Mobile devices are not targeted for the company side for now.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +9. Create a match if interested in a candidate's profile.
The company doesn't initiate the match. 
The company gives their "preferred soft-skills", and if a job seeker likes a company with which the soft skills are compatible, the match appears. 
The company decides to send a message to the job seeker afterwards.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +- **Candidate Inputs:**
The Candidate also provides his location.

2024-05-17 14:09 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +- In a future release, users will also be able to use the app on their personal computers. The minimum specifications laid down are:
When you use the term "users", I cannot understand if you're talking about jobseekers or companies. 
It's the case for all the times you used the word "user" when a feature is specific to a type of user.

2024-05-21 06:59 UTC, HiNett commented
Closing the Pull Request, in accordance with the rules in place. One pull request per day, if not finalized by the end of the day/weekend, it will be closed.

2024-05-21 06:59 UTC, closed without merging