Functional V0.3 (Images will be added after PR validation)
algosup/2023-2024-project-5-flutter-team-1 pull request #6
Opened 2024-05-22 13:50 UTC by PortetWilfried

2024-05-22 14:55 UTC, EnzoGuillouche requested changes
Some changes are requested.

2024-05-22 14:55 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +This document aims to provide a comprehensive overview of the "Adopt a Candidate" application. This application serves as a bridge between jobseekers and companies, with a unique feature of anonymity
Job-seekers should contain a dash.

2024-05-22 14:55 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +- **Job Seekers:** Citizens seeking employment, whether skilled or low-skilled, by highlighting their soft skills rather than formal qualifications. The goal is to help jobseekers find positions that
Same for job-seekers.

2024-05-22 14:55 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +7. On the homepage the jobseeker must like the company to initiate the match.
Same for job-seeker.

2024-05-22 14:55 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +8. Then the jobseeker needs to wait for a company to start a conversation.
Again.

2024-05-22 14:55 UTC, EnzoGuillouche commented on documents/functional_specifications/Functional Specification.md
> +**Example: Jobseeker's experience**
This is the last comment I write about job-seekers, look throughout the file for this mistake.

2024-05-24 12:17 UTC, PortetWilfried commented on documents/functional_specifications/Functional Specification.md
> +This document aims to provide a comprehensive overview of the "Adopt a Candidate" application. This application serves as a bridge between jobseekers and companies, with a unique feature of anonymity
I checked the spelling for jobseeker and it's jobseeker not job-seeker.

2024-05-24 12:19 UTC, EnzoGuillouche approved these changes
Merging approved.

2024-05-24 12:28 UTC, Mattstar64 approved these changes
Everything seems in order and all documentation criteria are checked. You can merge !

2024-05-24 12:29 UTC, NanaChocolat approved these changes

2024-05-24 12:29 UTC, merged